import crypto from 'crypto';
import { preparePrompt } from '../message.js';
const BASE='https://chatglm.cn/chatglm';
const SIGN_SECRET='8a1317a7468aa3ad86e997d08f3f31cb';
const DEFAULT_ASSISTANT_ID='65940acff94777010aa6b796';
const HEADERS={Accept:'text/event-stream','Content-Type':'application/json',Origin:'https://chatglm.cn','App-Name':'chatglm','X-App-Platform':'pc','X-App-Version':'0.0.1','X-Lang':'zh','User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/143 Safari/537.36'};
function uuid(){return crypto.randomUUID().replace(/-/g,'')}
function md5(s){return crypto.createHash('md5').update(s).digest('hex')}
export function generateSign(){ const A=Date.now().toString(), t=A.length, sum=A.split('').map(Number).reduce((a,b)=>a+b,0)-Number(A[t-2]); const a=sum%10; const timestamp=A.substring(0,t-2)+a+A.substring(t-1); const nonce=uuid(); return {timestamp,nonce,sign:md5(`${timestamp}-${nonce}-${SIGN_SECRET}`)}; }
export function parseGlmSse(text){ const events=[]; for (const block of String(text).split(/\n\n+/)) { const line=block.split('\n').find(l=>l.startsWith('data:')); if (!line) continue; const data=line.replace(/^data:\s*/,''); if (data==='[DONE]') continue; try { events.push(JSON.parse(data)); } catch {} } return events; }
export class GLMProvider {
  constructor(account){ this.account=account; this.refreshToken=account.refresh_token || account.refreshToken || account.token; this.accessToken=account.access_token || account.accessToken || ''; if(!this.refreshToken&&!this.accessToken) throw new Error('GLM token missing'); }
  async token(){ if (this.accessToken) return this.accessToken; const sign=generateSign(); const resp=await fetch(`${BASE}/user-api/user/refresh`, {method:'POST',headers:{...HEADERS,Authorization:`Bearer ${this.refreshToken}`,'X-Device-Id':uuid(),'X-Nonce':sign.nonce,'X-Request-Id':uuid(),'X-Sign':sign.sign,'X-Timestamp':sign.timestamp},body:'{}'}); const data=await resp.json().catch(()=>null); if(!resp.ok || !(data?.code===0 || data?.status===0) || !data?.result?.access_token) throw new Error(`GLM token refresh failed HTTP ${resp.status}: ${JSON.stringify(data).slice(0,200)}`); this.accessToken=data.result.access_token; return this.accessToken; }
  async complete({messages,modelCfg,tools,session}){ const access=await this.token(); const prompt=preparePrompt(messages,tools,{simpleTools:false,isMultiTurn:!!session.providerSessionId}); const sign=generateSign(); const body={ assistant_id: /^[a-z0-9]{24,}$/i.test(modelCfg.id)?modelCfg.id:DEFAULT_ASSISTANT_ID, conversation_id:session.providerSessionId||'', project_id:'', chat_type:'user_chat', messages:[{role:'user',content:[{type:'text',text:prompt}]}], meta_data:{ chat_mode:modelCfg.deepResearch?'deep_research':modelCfg.thinking?'zero':undefined, if_plus_model:true, is_networking:!!modelCfg.webSearch, platform:'pc', cogview:{rm_label_watermark:false} } }; const resp=await fetch(`${BASE}/backend-api/assistant/stream`, {method:'POST',headers:{...HEADERS,Authorization:`Bearer ${access}`,'X-Device-Id':uuid(),'X-Request-Id':uuid(),'X-Nonce':sign.nonce,'X-Sign':sign.sign,'X-Timestamp':sign.timestamp},body:JSON.stringify(body)}); const raw=await resp.text(); if(!resp.ok) throw new Error(`GLM HTTP ${resp.status}: ${raw.slice(0,200)}`); const events=parseGlmSse(raw); let text='', reasoning='', conv=''; for(const e of events){ conv ||= e.conversation_id || e.conversationId || e.data?.conversation_id || ''; text += e.delta || e.content || e.data?.content || e.parts?.map(p=>p.content||p.text||'').join('') || ''; reasoning += e.reasoning_content || e.thinking || ''; } return { text: text || raw, reasoning, providerSessionId: conv, parentMessageId:'', prompt }; }
}
